export type PageType =
  | 'inicio'
  | 'historia'
  | 'museo'
  | 'eventos'
  | 'torneos'
  | 'cumpleanos'
  | 'alquiler'
  | 'sat'
  | 'entradas'
  | 'galeria'
  | 'tienda'
  | 'contacto'
  | 'admin'
  | 'pago-completado';
